### ISSUE TITLE
executable bits not set for js script files

### ISSUE THREAD

**Issue by sam-github** [watilde/dep#7]
I quite like the idea of including a minimal installer in node core, so people can install npm (or yarn, though it still fails to install larger projects in my experience) globally with it later if they want. Doing some poking. This test run shows three problems:

1. executable bits not set (what I originally found)
2. on the second last run, dep hung for a minute until I interrupted it, but the other two runs it installed in a dozen or so seconds
3. unhandled promise rejection looks to be a bug
4. dep doesn't show deprecation messages, though this could be considered a feature, minimatch isn't a direct dependency, so its outside my control

```

sn/strong-cluster-control (master u=) % git clean -x -d
Removing node_modules/
sn/strong-cluster-control (master u=) % npm i; ls -l node_modules/eslint/bin/eslint.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
added 271 packages in 8.352s
-rwxrwxr-x 1 sam sam 2762 Apr 29  2016 node_modules/eslint/bin/eslint.js*
sn/strong-cluster-control (master u=) % git clean -x -d                               
Removing node_modules/
sn/strong-cluster-control (master u=) % dep i; ls -l node_modules/eslint/bin/eslint.js                                                                                        
Resolving dependencies
Installing dependencies
^C
sn/strong-cluster-control (master u=) % git clean -x -d                               
Removing node_modules/
sn/strong-cluster-control (master u=) % time dep install; ls -l node_modules/eslint/bin/eslint.js
Resolving dependencies
Installing dependencies
Installed 344 packages in 11.41s
dep install  6.01s user 0.95s system 57% cpu 12.191 total
-rw-rw-r-- 1 sam sam 2762 Apr 29  2016 node_modules/eslint/bin/eslint.js
sn/strong-cluster-control (master u=) % dep run pretest
(node:25609) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): /bin/sh: 1: eslint: Permission denied

(node:25609) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is all on Linux, recent ubuntu, x64, node 8.4.0

**Comment by sam-github** [comment]
Btw, I believe you have correctly identified the core feature set of npm for package consumers. I miss, a little, `dep test`, but `dep run test` is something I would probably get used to, and I'm happy it tried to run the pretest.

`dep ls lodash` (for example) is also useful for consumers, but if I have to troubleshoot your package tree, installing `npm` to get the full feature set is pretty reasonable, so I support leaving it out.

**Comment by gibfahn** [comment]
>I miss, a little, dep test, but dep run test is something I would probably get used to, and I'm happy it tried to run the pretest.

Or `dep r test` if you're lazy...

I will miss `npm it` though (`npm install && npm test`).

**Comment by sam-github** [comment]
I didn't even know `npm it` was a thing! Wow, too many easter eggs.

**Comment by watilde** [comment]
Hi Sam!

Thanks for reporting this :) Those are good points that should be fixed. I will open another issue to point this issue and I will answer per issue on it.

**Comment by watilde** [comment]
I just separated this issue into single tickets #16, #17, #18. Will work step by step :)
Let me know if I'm misunderstanding the issue. Thanks!

**Comment by sam-github** [comment]
@watilde the new tickets look good to me, but did you miss the most important issue?

> executable bits not set

This is more critical than all the other things, IMO, it makes the `dep run` command non-functional.

**Comment by watilde** [comment]
@sam-github Oops, I don't understand about it yet. Which part of the logs is about the `executable bits not set` issue?

**Comment by sam-github** [comment]
```
% npm i; ls -l node_modules/eslint/bin/eslint.js
-rwxrwxr-x 1 sam sam 2762 Apr 29  2016 node_modules/eslint/bin/eslint.js*

% time dep install; ls -l node_modules/eslint/bin/eslint.js
-rw-rw-r-- 1 sam sam 2762 Apr 29  2016 node_modules/eslint/bin/eslint.js
```

because of this, `dep run pretest` fails, because eslint is not executable
